urls.py
from django.conf.urls.defaults import *
from django.contrib import admin

from mezzanine.core.views import direct_to_template


admin.autodiscover()

# Add the urlpatterns for any custom Django applications here.
# You can also change the ``home`` view to add your own functionality to
# the project's homepage.
urlpatterns = patterns("",
    ("^admin/", include(admin.site.urls)),
    url("^$", direct_to_template, {"template": "index.html"}, name="home"),
    ("^", include("mezzanine.urls")),
)

# Adds ``MEDIA_URL`` to the context.
handler500 = "mezzanine.core.views.server_error"

gallery/models.py
from django.db import models
from mezzanine.pages.models import Page
from filebrowser_safe.fields import FileBrowseField

class Gallery(Page):
    notes = models.TextField("Notes")

class GalleryImage(models.Model):
    gallery = models.ForeignKey("Gallery")
    image = FileBrowseField("Image", max_length=200, 
            extensions=['.jpg','.png','.gif'])
    text = models.TextField(blank=True)

    class Admin:
        pass

    def __unicode__(self):
        return u'%s' % self.text

gallery/views.py
# Create your views here.

gallery/templates/gallery/gallery.html
<html>
    <head>
        <title>Gallery</title>
    </head>
    <body>
        <h1>{{ page.gallery.title }}</h1>
        <p>{{ page.gallery.notes }}</p>
        {% for galleryimage in page.gallery.galleryimage_set.all %}
        <img src="{{MEDIA_URL}}{{galleryimage.image}}" />
        {% endfor %}
    </body>
</html>

templates/base-0.html
{% load pages_tags mezzanine_tags i18n %}
<html>
<head>

    <meta http-equiv="Content-type" content="text/html; charset=utf-8" /> 
    <meta name="keywords" content="{% block meta_keywords %}{% endblock %}" /> 
    <meta name="description" content="{% block meta_description %}{% endblock %}" /> 
    <title>{% block meta_title %}{% endblock %}{% if settings.SITE_TITLE %} | {{ settings.SITE_TITLE }}{% endif %}</title>

    {% if "mezzanine.blog"|is_installed %}
    <link rel="alternate" type="application/rss+xml" title="RSS" 
        href="{% url blog_post_feed "rss" %}" />
    <link rel="alternate" type="application/atom+xml" title="Atom"  
        href="{% url blog_post_feed "atom" %}" />
    {% endif %}

    <link rel="stylesheet" href="{{ MEDIA_URL }}css/960.css" type="text/css" />
    <link rel="stylesheet" href="{{ MEDIA_URL }}css/reset.css" type="text/css" />
    <link rel="stylesheet" href="{{ MEDIA_URL }}css/global.css" type="text/css" />
    {% block extra_head %}{% endblock %}

</head>
<body id="{% block body_id %}{% endblock %}">

{% if settings.SITE_TITLE or settings.SITE_TAGLINE %}
<div id="grid-header">
    {% if settings.SITE_TITLE %}
    <h1>{{ settings.SITE_TITLE }}</h1>
    {% endif %}
    {% if settings.SITE_TAGLINE %}
    <h2>{{ settings.SITE_TAGLINE }}</h2>
    {% endif %}
</div>
{% endif %}

<div id="grid-top">
    {% page_menu "pages/menus/primary.html" %}
</div>

<div class="container_12 clearfix">

    <div id="grid-left" class="grid_3 grid">
        {% page_menu "pages/menus/tree.html" %}
    </div>

    <div id="grid-middle" class="grid_6 grid">
        <div class="gutter">
            <h1>{% block title %}{% endblock %}</h1>
            <div id="breadcrumb-menu">
                {% block breadcrumb_menu %}
                    {% page_menu "pages/menus/breadcrumb.html" %}
                {% endblock %}
            </div>
            {% block main %}{% endblock %}
        </div>
    </div>

    <div id="grid-right" class="grid_3 grid">
        {% include "includes/search.html" %}
        {% block right_panel %}
            {% if "mezzanine.twitter"|is_installed %}
            {% include "twitter/tweets.html" %}
            {% endif %}
        {% endblock %}
        <p class="mezzanine">
            {% trans "Powered by" %} 
            <a href="http://mezzanine.jupo.org">Mezzanine</a><br />
            <a href="{% url set_device "mobile" %}?next={{ request.path }}">
                {% trans "View Mobile Site." %}
            </a>
        </p>
    </div>

</div>

<div id="grid-bottom">
    <div class="container_12 clearfix">
        <div class="grid_3">&nbsp;</div>
        <div class="grid_6 push_3 grid">
            {% page_menu "pages/menus/footer.html" %}
        </div>
    </div>
</div>

{% include "includes/footer_scripts.html" %}

</body>
</html>

templates/base.html
{% load pages_tags mezzanine_tags i18n %}
<html>
    <head>

        <meta http-equiv="Content-type" content="text/html; charset=utf-8" /> 
        <meta name="keywords" content="{% block meta_keywords %}{% endblock %}" /> 
        <meta name="description" content="{% block meta_description %}{% endblock %}" /> 
        <title>{% block meta_title %}{% endblock %}{% if settings.SITE_TITLE %} | {{ settings.SITE_TITLE }}{% endif %}</title>

        {% if "mezzanine.blog"|is_installed %}
        <link rel="alternate" type="application/rss+xml" title="RSS" 
        href="{% url blog_post_feed "rss" %}" />
        <link rel="alternate" type="application/atom+xml" title="Atom"  
        href="{% url blog_post_feed "atom" %}" />
        {% endif %}

        <link rel="stylesheet" href="{{ MEDIA_URL }}css/960.css" type="text/css" />
        <link rel="stylesheet" href="{{ MEDIA_URL }}css/reset.css" type="text/css" />
        <link rel="stylesheet" href="{{ MEDIA_URL }}css/base.css" type="text/css" />
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js" type="text/javascript"></script>
        <script src="{{ MEDIA_URL }}js/base.js"></script>
        {% block extra_head %}{% endblock %}

    </head>
    <body id="{% block body_id %}{% endblock %}">

        <div id="header">
            <div id="header-strip">
                <div class="container_12" >
                    <div class="grid_4">
                        <a href="/"><img id="logo" src="{{MEDIA_URL}}img/alogo-sub.png" /></a>
                    </div>
                    <div class="grid_8">
                        {% page_menu "pages/menus/dropdown.html" %}
                    </div>
                </div>
                <div class="container_12">
                <div id="search">
                    {% include "includes/sexysearch.html" %}
                </div>
            </div>
            </div>
        </div>

        <div class="container_12 clearfix" id="container">

            <div class="grid_8 suffix_1" id="content">
                <div id="tab">
                <h1>{% block title %}{% endblock %}</h1>
                <div id="breadcrumb-menu">
                    {% block breadcrumb_menu %}
                    {% page_menu "pages/menus/breadcrumb.html" %}
                    {% endblock %}
                </div>
            </div>
                {% block main %}{% endblock %}
            </div>

            <div class="grid_3" id="sidebar">
                <p class="mezzanine">
                {% trans "Powered by" %} 
                <a href="http://mezzanine.jupo.org">Mezzanine</a><br />
                <a href="{% url set_device "mobile" %}?next={{ request.path }}">
                    {% trans "View Mobile Site." %}
                </a>
                </p>
            </div>

        </div>

        <div id="footer">
            <div id="footer-content">
                <p>This site &copy; The Alliance for Appalachia, 2011<br />
                Web design by <a href="http://garrett.im">Garrett Robinson</a></p>
            </div>
        </div>
    </body>
</html>

templates/index.html
{% extends "base.html" %}

{% load i18n %}

{% block meta_title %}{% trans "Home" %}{% endblock %}

{% block title %}
{% trans "Welcome to the Alliance for Appalachia" %}
{% endblock %}

{% block main %}
<p>The Alliance for Appalachia is a regional alliance with the goals of ending a devastating form of coal mining called mountaintop removal coal mining, putting a halt to destructive coal technologies and supporting a sustainable, just economy in Appalachia.</p>
<p align="center"><iframe width="560" height="349" src="http://www.youtube.com/embed/XyzwCKoLhDo" frameborder="0" allowfullscreen></iframe></p>
<p>Beginning in the spring of 2006, thirteen organizations from five states in Central Appalachia have worked together to build this alliance. We are pursing a number of complementary strategies including grassroots organizing, leadership development, strategic communications, alliance building, research, litigation, and more.</p>
{% endblock %}

templates/mobile/base.html
{% load pages_tags mezzanine_tags i18n %}
<!doctype html>
<html>
<head>

    <meta http-equiv="Content-type" content="text/html; charset=utf-8" /> 
    <meta name="keywords" content="{% block meta_keywords %}{% endblock %}" /> 
    <meta name="description" content="{% block meta_description %}{% endblock %}" /> 
    
    <meta name="viewport" content="initial-scale=1, maximum-scale=1">
    
    <title>{% block meta_title %}{% endblock %}</title>
    
    {% if "mezzanine.blog"|is_installed %}
    <link rel="alternate" type="application/rss+xml" title="RSS" 
        href="{% url blog_post_feed "rss" %}" />
    <link rel="alternate" type="application/atom+xml" title="Atom"  
        href="{% url blog_post_feed "atom" %}" />
    {% endif %}
    <link rel="apple-touch-icon" href="" />     
        
    <link rel="stylesheet" href="{{ MEDIA_URL }}css/global-mobile.css" type="text/css" />

    <link rel="stylesheet" href="http://code.jquery.com/mobile/1.0a2/jquery.mobile-1.0a2.min.css" />
    <script src="http://code.jquery.com/jquery-1.4.4.min.js"></script>
    <script src="http://code.jquery.com/mobile/1.0a2/jquery.mobile-1.0a2.min.js"></script>
    
    {% block extra_head %}{% endblock %}

</head>
<body id="{% block body_id %}{% endblock %}">
<div data-role="page" data-theme="d">
    <div data-role="header">
        <h1>{% block title %}{% endblock %}</h1>
        <a class="home" data-role="button" data-icon="star" href="{% url home %}">{% trans "Home" %}</a>
    </div>
    
    {% page_menu "pages/menus/mobile.html" %}
    
    <div data-role="content">
        {% block main %}{% endblock %}
    </div>
    
    <div data-role="footer">
        <div data-role="content" align="center">
        	{% include "includes/search.html" %}
            <p>{% trans "Powered by" %} <a href="http://mezzanine.jupo.org" rel="external">Mezzanine</a></p>
            <p><a href="{% url set_device "default" %}?next={{ request.path }}" rel="external">{% trans "View Full Site" %}</a></p>
        </div>
    </div>
</div>

{% include "includes/footer_scripts.html" %}

</body>
</html>


templates/mobile/blog/blog_post_detail.html
{% extends "blog/blog_post_list.html" %}
{% load mezzanine_tags i18n %}

{% block meta_title %}{{ blog_post.title }}{% endblock %}

{% block meta_keywords %}{% metablock %}
{% for keyword in blog_post.keywords.all %}
    {% if not forloop.first %}, {% endif %}
    {{ keyword }}
{% endfor %}
{% endmetablock %}{% endblock %}

{% block meta_description %}{% metablock %}
{{ blog_post.description }}
{% endmetablock %}{% endblock %}

{% block title %}
{% editable blog_post.title %}{{ blog_post.title }}{% endeditable %}
{% endblock %}

{% block main %}

<p>
    <em>
        {% trans "Posted by" %}
        <strong>
            {% with blog_post.user as author %}
            <a href="{% url blog_post_list_author author %}"
                >{{ author.get_full_name|default:author.username }}</a>
            {% endwith %}
        </strong>
        {{ blog_post.publish_date|timesince }} {% trans "ago" %}
    </em>
</p>

{% editable blog_post.content %}
{{ blog_post.content|safe }}
{% endeditable %}

{% with blog_post.keywords.all as tags %}
{% if tags %}
<div class="tags">
    {% trans "Tags" %}: 
    <ul>
        {% for tag in tags %}
        <li><a href="{% url blog_post_list_tag tag.slug %}" 
            class="tag-weight-{{ tag.weight }}">{{ tag }}</a></li>
        {% endfor %}
    </ul>
</div>
{% endif %}
{% endwith %}

{% set_short_url_for blog_post %}
<div data-inline="true" class="share-links">
	{% trans "Share this on:" %} 
    <a target=_"blank" href="http://twitter.com/home?status={{ blog_post.short_url|urlencode }}%20{{ blog_post.title|urlencode }}">Twitter</a>
    {% trans "or" %} 
    <a target=_"blank" href="http://facebook.com/sharer.php?u={{ request.build_absolute_uri }}&t={{ blog_post.title|urlencode }}">Facebook</a>
</div>

{% if use_disqus %}
{% include "blog/includes/disqus_comments.html" %} 
{% else %}
{% include "blog/includes/comments.html" %} 
{% endif %}

{% endblock %}



templates/mobile/blog/blog_post_list.html
{% extends "base.html" %}
{% load i18n mezzanine_tags blog_tags %}

{% block meta_title %}{{ blog_page.title }}{% endblock %}

{% block meta_keywords %}{% metablock %}
{% for keyword in blog_page.keywords.all %}
    {% if not forloop.first %}, {% endif %}
    {{ keyword }}
{% endfor %}
{% endmetablock %}{% endblock %}

{% block meta_description %}{% metablock %}
{{ blog_page.description }}
{% endmetablock %}{% endblock %}

{% block title %}
{% editable blog_page.title %}{{ blog_page.title }}{% endeditable %}
{% endblock %}

{% block main %}
<ul data-role="listview" data-inset="true" data-splittheme="a">
    {% for blog_post in blog_posts.object_list %}
		<li>
        {% editable blog_post.title blog_post.publish_date %}
                <h2 class="blog-post-title"><a href="{% url blog_post_detail blog_post.slug %}">{{ blog_post.title }}</a></h2>
                <em class="since">{{ blog_post.publish_date|timesince }} {% trans "ago" %}</em>
        {% endeditable %}
        </li>
    {% endfor %}    
</ul>
{% pagination_for blog_posts %} 

{% endblock %}



templates/mobile/blog/includes/comments.html
{% load i18n blog_tags %}

<div data-role="collapsible" data-collapsed="true">
    <h3>{% trans "Comments" %} ({{ blog_post.num_comments }})</h3>
	{% blog_comments_for blog_post %}
    <form method="post" class="comment" id="comment" action="#comment">
        {% csrf_token %}
        <table>
        {% if request.POST.replied_to %}
        {{ unposted_comment_form.as_table }}
        {% else %}
        {{ posted_comment_form.as_table }}
        {% endif %}
        <tr><td colspan="2">
        <input class="button" type="submit" value="{% trans "Comment" %}" />
        </td></tr>
        </table>
    </form>
</div>

templates/mobile/blog/includes/comments_thread.html
{% load i18n blog_tags %}

<ul class="comments">
    {% for comment in comments_thread %}
    <li id="comment-{{ comment.id }}"{% if comment.by_author %} 
        class="author"{% endif %}>
        {% if comment.approved %}
        <em>
            <strong>
            {% if comment.website %}
            <a href="{{ comment.website }}">
                <img src="{% gravatar_url comment.email_hash %}" />   
                {{ comment.name }}
            </a>
            {% else %}
            <img src="{% gravatar_url comment.email_hash %}" />{{ comment.name }}
            {% endif %}
            </strong>
            {{ comment.time_created|timesince }} {% trans "ago" %}
        </em>
        <p>{{ comment }}</p>
		<div data-role="collapsible" data-collapsed="true">
            <h4>{% trans "Reply" %}</h4>
            <form method="post" id="reply-{{ comment.id }}"
                class="comment{% ifequal replied_to comment.id %} posted{% endifequal %}">
                {% csrf_token %}
                <table>
                {% ifequal replied_to comment.id %}
                {{ posted_comment_form.as_table }}
                {% else %}
                {{ unposted_comment_form.as_table }}
                {% endifequal %}
                <tr><td colspan="2">
                <input type="hidden" name="replied_to" value="{{ comment.id }}" />
                <input class="button" type="submit" value="{% trans "Reply" %}" />
                </td></tr>
                </table>
            </form>
        </div>
        {% else %}
        <p>
            {% if settings.COMMENTS_DEFAULT_APPROVED %}
            {% trans "Comment deleted" %}
            {% else %}
            {% trans "Comment awaiting approval" %}
            {% endif %}
        </p>
        {% endif %}
        {% blog_comments_for comment %}
    </li>
    {% endfor %}
    {% if no_comments %}
    <li>{% trans "There are currently no comments" %}</li>
    {% endif %}
</ul>


templates/mobile/includes/footer_scripts.html
{% if settings.GOOGLE_ANALYTICS_ID %}
<script> 

var _gaq = [['_setAccount', '{{ settings.GOOGLE_ANALYTICS_ID }}'], ['_trackPageview']];

(function(d, t) {
    var g = d.createElement(t),
        s = d.getElementsByTagName(t)[0];
    g.async = true;
    g.src = '//www.google-analytics.com/ga.js';
    s.parentNode.insertBefore(g, s);
})(document, 'script');

</script>
{% endif %}

templates/mobile/includes/pagination.html
{% load i18n %}

{% if current_page.has_previous or current_page.has_next %}
<fieldset class="ui-grid-a">
    <div class="ui-block-a">
        {% if current_page.has_previous %}<a href="?page={{ current_page.previous_page_number }}&{{ querystring }}" data-role="button" data-icon="arrow-l" data-iconpos="left">{% trans "Previous" %}</a>{% endif %}
    </div>
    <div class="ui-block-b">
	    {% if current_page.has_next %}<a href="?page={{ current_page.next_page_number }}&{{ querystring }}" data-role="button" data-icon="arrow-r" data-iconpos="right">{% trans "Next" %}</a>{% endif %}
    </div>
</fieldset>
{% endif %}

templates/mobile/includes/search.html
{% load i18n %}

<form method="get" action="{% url search %}" id="search">
    <input type="search" name="q" placeholder="{% trans "Search"%}..." value="{{ request.REQUEST.q }}">
    <p class="help">{% trans "Use "%} "{% trans "quotes" %}" {% trans " for exact phrases, + to make a word or phrase required, and - to exclude a word or phrase." %}"</p>
</form>



templates/mobile/index.html
{% extends "base.html" %}

{% load i18n %}

{% block title %}
{% trans "Home" %}
{% endblock %}

{% block main %}
{% trans "This is the mobile homepage." %}
{% endblock %}

templates/mobile/pages/contentpage.html
{% extends "pages/page.html" %}

{% load mezzanine_tags %}

{% block main %}{{ block.super }}

{% editable page.contentpage.content %}
{{ page.contentpage.content|safe }}
{% endeditable %}

{% endblock %}

templates/mobile/pages/form.html
{% extends "pages/page.html" %}

{% load mezzanine_tags %}

{% block main %}{{ block.super }}

{% if request.GET.sent %}
    {% editable page.form.response %}
    {{ page.form.response|safe }}
    {% endeditable %}
{% else %}
    {# editable page.form.content #}
    {{ page.form.content|safe }}
    {# endeditable #}
    <form method="post" class="form"{% if form.is_multipart %} enctype="multipart/form-data"{% endif %}>
        {% csrf_token %}
        {{ form.as_p }}
        <input class="button" type="submit" value="{{ page.form.button_text }}" />
    </form>
{% endif %}

{% endblock %}


templates/mobile/pages/menus/mobile.html
{% load i18n pages_tags %}

{% spaceless %}
{% if page_branch %}
{% for page in page_branch %}

	{% if page.is_primary and forloop.first %}
	<nav>
    <ul class="mobile-menu" data-role="listview" data-inset="true">
    {% endif %}

		{% if page.is_current_or_ascendant and not page.is_child %}
		{% page_menu page %}
		{% endif %}
		
		{% if page.is_child %}
		<li class="
			{% if forloop.first %} first{% endif %}
			{% if forloop.last %} last{% endif %}"
			id="mobile-menu-{{ page.html_id }}">
			<a href="{% url page page.slug %}" rel="external">{{ page.title }}</a>
		</li>
		{% endif %}

	{% if page.is_primary and forloop.last %}
	</ul></nav>
	{% endif %}
{% endfor %}
{% endif %}
{% endspaceless %}

templates/mobile/pages/page.html
{% extends "base.html" %}
{% load mezzanine_tags %}

{% block meta_title %}{{ page.title }}{% endblock %}

{% block meta_keywords %}{% metablock %}
{% for keyword in page.keywords.all %}
    {% if not forloop.first %}, {% endif %}
    {{ keyword }}
{% endfor %}
{% endmetablock %}{% endblock %}

{% block meta_description %}{% metablock %}
{{ page.description }}
{% endmetablock %}{% endblock %}

{% block title %}
{% editable page.title %}{{ page.title }}{% endeditable %}
{% endblock %}

{% block main %}
{% endblock %}

templates/mobile/search_results.html
{% extends "base.html" %}

{% load i18n mezzanine_tags %}

{% block meta_title %}{% trans "Search Results" %}{% endblock %}
{% block title %}{% trans "Search Results" %}{% endblock %}

{% block main %}

<p>
{% ifequal results.paginator.count 0 %}
{% trans "No results were found matching your query: " %}<em>{{ query }}</em>
{% else %}
{% trans "Showing" %} {{ results.start_index }} {% trans "to" %} {{ results.end_index }} {% trans "of" %}
{{ results.paginator.count }} {% trans "results matching your query:" %} <em>{{ query }}</em>
{% endifequal %}
</p>

<div id="search-results">
    {% for result in results.object_list %}
    <h5><a href="{{ result.get_absolute_url }}">{{ result }}</a></h5>
    {{ result.description|truncatewords_html:20|safe }}
    <a href="{{ result.get_absolute_url }}">{% trans "read more" %}</a>
    {% endfor %}
</div>

{% pagination_for results %}

{% endblock %}

templates/pages/gallery.html
{% extends "base.html" %}
{% block meta_title %}Gallery{% endblock %}
{% block extra_head %}
<link rel="stylesheet" href="{{MEDIA_URL}}css/jquery.lightbox-0.5.css" type="text/css" media="screen" />
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js" type="text/javascript"></script>
<script src="{{MEDIA_URL}}js/jquery.lightbox-0.5.js" type="text/javascript"></script>
<!-- Load lightbox -->
<script type="text/javascript">
    $(function () {
            $('#gallery a').lightBox({
imageLoading: '{{MEDIA_URL}}img/lightbox-ico-loading.gif',
imageBtnClose: '{{MEDIA_URL}}img/lightbox-btn-close.gif',
imageBtnPrev: '{{MEDIA_URL}}img/lightbox-btn-prev.gif',
imageBtnNext: '{{MEDIA_URL}}img/lightbox-btn-next.gif',
imageBlank: '{{MEDIA_URL}}img/lightbox-blank.gif'
});
            });
</script>
{% endblock %}

{% block main %}
<h1>{{ page.gallery.title }}</h1>
<p>{{ page.gallery.notes }}</p>
<div id="gallery">
    {% load fb_versions %}
    {% for galleryimage in page.gallery.galleryimage_set.all %}
    <a href="{{galleryimage.image}}" title="{{galleryimage.text}}">
        <img src="{% version galleryimage.image.path "fb_thumb" %}" />
    </a>
    {% endfor %}
</div>
{% endblock %}

templates/pages/menus/dropdown.html
{% load pages_tags i18n %}

{% spaceless %}
{% if page_branch %}
{% if branch_level == 0 %}
<ul id="nav">
{% else %}
<ul>
{% endif %}
    {% for page in page_branch %}
    {% if page.in_navigation %}
    <li>
    <a href="{% url page page.slug %}">{{ page.title }}</a>
    {# subpages here #}
    {% if settings.PAGES_MENU_SHOW_ALL or page.is_current_or_ascendant %}
    {% page_menu page %}
    {% endif %}
    </li>
    {% endif %}
    {% endfor %}
</ul>
{% endif %}
{% endspaceless %}